### ISSUE TITLE
Reduce points on obstacales even if life is 0

### ISSUE THREAD

**Issue by emesika** [RedHat-Israel/ROSE#111]
Currently there is no life reduce if car reaches obstacles and failed to handle it while its life is 0
This should be change to reducing points on failure to handle a obstacle

**Comment by nirs** [comment]
We don't have "life" any more. Eli, is this relevant now?

**Comment by nirs** [comment]
@emesika is this relevant now?

**Comment by nirs** [comment]
Closing old issues
