### ISSUE TITLE
Complete web interface

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#172]
The web interface do not render the obstacles and cars yet.

Should be pretty easy to port the python code for this to javascript.

**Comment by nirs** [comment]
#180 added obstacles and cars, but we are still missing:
- car labels
- finish line

**Comment by nirs** [comment]
#182 adds the finish line

**Comment by nirs** [comment]
#185 Adds the missing labels, once merged we can close this issue.

**Comment by rollandf** [comment]
Done
