### ISSUE TITLE
OpenShift integration

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#175]
Provide an easy way to deploy a ROSE server on https://openshift.io/

**Comment by cben** [comment]
you want something like https://blog.openshift.com/updated-openshift-deploy-buttons/ but for openshift 3...
I'm afraid Heroku integration — with a Heroku Button https://devcenter.heroku.com/articles/heroku-button — can be friendlier to beginners who want to Just Run It.

**Comment by shiramax** [comment]
I'm Closing this issue because it's open too long and we don't have the need or the capacity to work on it.
please feel free to re-open in if you feel otherwise.
