### ISSUE TITLE
Remove pygame code

### ISSUE THREAD

**Issue by rollandf** [RedHat-Israel/ROSE#186]
Since we have now a web interface, the pygame code is not needed.

The changes needed:
- remove the rendering code in rose/client/game.py
- remove the module rendering the components in rose/client/
- remove the configuration options in rose/common/config.py needed only by the client
- move modules from rose/common to rose/server that are used now only by the server
- remove pygame from the requirements.txt / Pipfile

Note: removing code without leaving unused stuff is not easy.

**Comment by nirs** [comment]
Fixed in #219.
