### ISSUE TITLE
Heroku integration

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#187]
Beni suggests in #175 that it will be easier to integrate with Heroku: 
https://devcenter.heroku.com/articles/heroku-button

The goal of this integration is allow anyone to deploy the rose-server on Heroku with few clicks.

The expected flow:
1. User clicks a deploy-on-heroku button in the project README
2. System open Heroku deploy page, with most parameters already filled up
3. User enter only the details that cannot be automated, such as application name (e.g. my-rose-server)
4. User confirm the deployment on Heroku
5. Application is deployed on Heruku, ready to accept connections from rose-client(s) on my-rose-server.herokuapp.com:8888, and showing the game UI at http://my-rose-server.herokuapp.com:8880/

Deployment details:
- Install the rose/common and rose/server packages
  - rose/client is not needed, but it is ok to install it for simplicity
- install the rose-server script
- When the application starts, rose-server should run
- When the application stops, rose-server process should terminate
- The Heroku instance should allow incoming traffic to ports 8888 (client port) and 8880 (web port)

Testing the deployment:
1. Open  http://my-rose-server.herokuapp.com:8880/ - should show an empty game
2. Create driver.py module with the server address:
```
$ cat driver.py
from rose.common import obstacles, actions

server_address = "my-rose-server.herokuapp.com"
driver_name = "My Driver"

def drive(world):
    return actions.NONE
```
3. Connect client to server:
```
./rose-client driver.py
```
4. Start the game in the web UI

The game should run, showing the connected client.

I'm not sure all this is possible, will needs some research.

**Comment by mayukh18** [comment]
Taking this up.

**Comment by nirs** [comment]
Thanks @mayukh18!

**Comment by shiramax** [comment]
I'm Closing this issue because it's open too long and we don't have the need or the capacity to work on it.
please feel free to re-open in if you feel otherwise.
