### ISSUE TITLE
Convert prints to logging

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#190]
Replace the non-portable print calls with logging.

**Comment by moshe742** [comment]
hacktoberfest tlv shotgun

**Comment by Abelarm** [comment]
I could work on this if noone already started

**Comment by nirs** [comment]
@Abelarm @moshe742 started to work on the rose.server package - do you want to fix this in the rose.client and/or rose.common package?

**Comment by Abelarm** [comment]
sure i'll start with client

**Comment by nirs** [comment]
Thanks @Abelarm, waiting for your PR :+1:

**Comment by Abelarm** [comment]
@nirs sorry for late but I can only code at night and weekends...
take a look and tell me if are there any change you need me to do 👍

**Comment by nirs** [comment]
We stil have some prints in the client package and in the rose-admin tool.

Waiting for a contributor to do the last clean ups :-)

**Comment by nirs** [comment]
@moshe742 do you want to complete this issue?
