### ISSUE TITLE
Modernize imports

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#192]
Replace the old imports like:

````
import track
````
With modern imports:
```
from rose.server import track
```
Or:
```
from . import track
```

**Comment by nirs** [comment]
@moshe742, can you post your PR for the server package?

**Comment by moshe742** [comment]
Done the PR

**Comment by nirs** [comment]
@moshe742 we need the same change also in the client and common packages, @andrew-jung sent #198

**Comment by moshe742** [comment]
Should I start on both or only common (since @andrew-jung works on client)?

**Comment by nirs** [comment]
@moshe742 andrew sent both server and client chages, but not common, so you can work on common.

**Comment by moshe742** [comment]
In common there is only one import which is written as
`from rose.common import error`
Should I make the change for consistency or keep this?
That is the only place we do an import from this package so except this there is no need for a change on the imports

**Comment by nirs** [comment]
@moshe742 having consistent import is nice, please post another PR for this.

**Comment by nirs** [comment]
@moshe742, can complete this PR?

**Comment by nirs** [comment]
@moshe742, I merged your PR, do you want to complete the client package?

**Comment by moshe742** [comment]
yes, will open a PR soon

**Comment by nirs** [comment]
We have one import to fix in the common package.
