### ISSUE TITLE
Update readme for new makefile

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#195]
The readme show how to run the project installed using pip, we have now pipenv support and a makefile making it much easier to use.

**Comment by PragyaM** [comment]
Hi there! I'm keen to pick up this task :)

**Comment by nirs** [comment]
Hi @PragyaM, you are welcome!

**Comment by surajpaib** [comment]
Hey, @PragyaM. Just read your comment on the thread. I can close the issue if you'd like to send a PR.

**Comment by PragyaM** [comment]
Hey @surajpaib - that's all good! I don't want to double up on work so I'll find something else to work on :)

**Comment by nirs** [comment]
Playing with the makefile show that it is not the right solution, so I'm closing this issue as wontfix.
