### ISSUE TITLE
Add flake8 to the travis build

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#218]
flake8 includes both pyflakes (finding code quality issues) and pycodestyle (finding code style issues). We want to fail the build if a pull request introduce such issues.

This task should be done in several steps:
1. Add flake8 to travis - the build will probably fail at this point
2. Fix easy issues
3. Silence issues which are hard to fix using #noqa comments
4. Silence unwanted warnings using flake8 configuration file

It should be possible to run flake8 locally without any command line options.

Related docs:
- http://flake8.pycqa.org/en/latest/
- https://docs.travis-ci.com/user/languages/python/

**Comment by eric-horvat** [comment]
I'll give this a go

**Comment by eric-horvat** [comment]
I think I can do this one

**Comment by nirs** [comment]
@eric-horvat, that would be awesome :+1:

**Comment by nirs** [comment]
Fixed by #223
