### ISSUE TITLE
Provide server address as a parameter from command line

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#221]
Currently the server address is specified in the driver module. This does not work well in the classroom, when students have to modify the server address many times.

After discussing this in #163, we agreed on this command line inteface:
```
./rose-client [-h|--help] [-s|--server SERVER] DRIVER
```
- If the server is not specified in the command line, fallback to driver module.
- if server is not specified anywhere, use localhost
- If server is specified both in command line and driver module, command line wins (silently)

The admin tool should be modified to use the command line interface.

Relevant docs:
- https://docs.python.org/3/library/argparse.html

**Comment by GudarJs** [comment]
May I help you with this issue?
Is there any contribution guideline that I need to follow?

**Comment by nirs** [comment]
Hi @GudarJs, @rollandf is working on this, see #163. Maybe you like to complete that PR?

**Comment by GudarJs** [comment]
It would be great! I will check it today on my free time.
Thank you!
