### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#245]
It may help some contributors to feel better about the project. Find and reuse code of conduct from another project.

**Comment by lekum** [comment]
Can I take this one?

**Comment by rollandf** [comment]
@lekum sure, go ahead

**Comment by lekum** [comment]
Any email address to report unacceptable behavior?

**Comment by rollandf** [comment]
Use mine: frolland@redhat.com

**Comment by nirs** [comment]
@lekum you can add my email also: nirsof at gmail.com

**Comment by rollandf** [comment]
#246 is resolving this issue.
Thanks a lot @lekum for this PR !!
We would be happy if you will get time to contribute again.
