### ISSUE TITLE
Avoid useless game without players

### ISSUE THREAD

**Issue by rollandf** [RedHat-Israel/ROSE#263]
If all the drivers disconnect, the game still runs for no reason.
The game should stop.

**Comment by nirs** [comment]
I think we can solve it differently - when one player disconnects, the other player wins, and the game stops.

If we go in this way, starting a game should be possible only when 2 players are connected.

**Comment by emesika** [comment]
+1

**Comment by rollandf** [comment]
I have seen a lot of students running their driver only while testing their code.
I don't think that adding a limitation of two client is useful.

**Comment by nirs** [comment]
@rollandf, good point about single user usage for training.

So I think the changes needed are:
- frontend: Enable the "Start" button only when at least one player is connected
- frontend: Render "No player connected" message if no player is connected.
- backend: fail start() if no player is connected
- backend: When a player disconnects, stop the game if it was the last player

**Comment by nirs** [comment]
Fixed by #273.
