### ISSUE TITLE
Improve logging format

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#268]
Current logging format is not very useful:

Client:
```
$ ./rose-client -s 10.35.0.197 examples/score.pyc 
INFO:main:Please open http://10.35.0.197:8880 to watch the game.
```
Server:
```
$ ./rose-server 
INFO:main:starting server
INFO:game:add player: u'Score', lane: 1, car: 2
```

I think in both cases we like to have something like:

```
2017-10-31 19:00:00,000 INFO  [logger] message ... (func:lineno)
```

**Comment by obernardovieira** [comment]
since the logger will be the same everywhere, can I put the logger config inside a specific file? I dont like this way 😋

**Comment by nirs** [comment]
@obernardovieira good idea, rose/common/config.py exists for common configuration.
