### ISSUE TITLE
No sound on android

### ISSUE THREAD

**Issue by nirs** [RedHat-Israel/ROSE#270]
When running the web UI on android 7, sound does not play.
Maybe rose/res/soundtrack/Nyan_Cat.ogg should use another encoder?

@devmattrick any clue about this?

**Comment by devmattrick** [comment]
Android will only allow audio to be played if its initiated by a user gesture (much like how popup blockers work). I suppose the only real solution is to allow it to be toggled on with the mute/ unmute button.

**Comment by nirs** [comment]
Sound on/off button will solve this issue then. Do you plan to respin your patches for #231?

**Comment by EgorLu** [comment]
https://github.com/RedHat-Israel/ROSE/pull/330 might solve this as well.
