### ISSUE TITLE
Recompile the example drivers

### ISSUE THREAD

**Issue by EgorLu** [RedHat-Israel/ROSE#332]
Currently the example driver files don't run.
My assumption is that with the transition to Python 3, the driver files need to be recompiled.

If someone still has their source code, it's a minute's work. Otherwise they could be reverse-engineered / decompiled back into source code, but that might be an overkill.

**Comment by rollandf** [comment]
Hi,
Can you tell me which ones, I will look if I have the sources.
Thanks

**Comment by EgorLu** [comment]
Hi Fred,
It's [score.pyc](https://github.com/RedHat-Israel/ROSE/blob/master/examples/score.pyc) and [zigzag.pyc](https://github.com/RedHat-Israel/ROSE/blob/master/examples/zigzag.pyc)
